spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: file://C:\Users\Dimitar Rachev\DemoProjects\event-driven-microservices\config-server-repository
          clone-on-start: true
    fail-fast: true
